version: "3.7"

# usage:
# sudo docker-compose build -d
# sudo docker-compose up -d

services:
  mongo:
    container_name: gagot-app-mongo-dev
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT_NAME}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASS}
    networks:
      - gagot-app-network
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  mongo-express:
    container_name: gagot-app-mongo-express
    image: mongo-express
    depends_on:
      - mongo
    networks:
      - gagot-app-network
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev

      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_ADMIN_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_ADMIN_PASS}

      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_AUTH_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_AUTH_PASS}
    ports:
      - '8081:8081'
    volumes:
      - ./data:/data/db

  redis:
    container_name: gagot-app-redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    restart: always
    ports:
      - ${REDIS_PORT_OUT}:${REDIS_PORT_IN}
    networks:
      - gagot-app-network
    volumes:
      - ./redis-data:/data

networks:
  gagot-app-network:
    driver: bridge

