export enum FacilitiesEnum {
  Wifi = 'Wifi',
  Fireplace = 'Fireplace',
  ParkingLot = 'ParkingLot',
  Pool = 'Pool',
  Sauna = 'Sauna',
  Cameras = 'Cameras',
  FitnessCenter = 'FitnessCenter',
  SmartControl = 'SmartControl',
  Boiler = 'Boiler',
  Lawn = 'Lawn',
  TennisCourt = 'TennisCourt',
  DualSinks = 'DualSinks',
  Jacuzzi = 'Jacuzzi',
  TennisCourts = 'TennisCourts',
}
